name: Kdot
favicon: null
layout_spectrum: 0.2475475079845637
typography_spectrum: 0.38445681636221707
title: >-
  KDOT è un modo per dire OK. Sì, punto. Cioè basta così, va bene, ce lo faremo
  andare bene. Punto. 
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6148905649315566
  lightness: 0.4538767081685364
  saturation: 0.4935928867198527
  rhythmicContrast: 0.5761662814766169
purpose: []
